version: "3.0"

volumes:
  mongo-keys:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:

networks:
  replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24

services:
  #use this one but this image is old one
  # mongo-keys:
  #   image: depop/openssl-bats
  #   volumes:
  #     - mongo-keys:/mongo-conf
  #   command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'
  
  #Use this one as it will use latest one with alpine image (this is for creating keyfile and mounting that in places also does keyfile rotation)
  mongo-keys:
    image: alpine
    volumes:
      - mongo-keys:/mongo-conf
    command: 'sh -c "apk add --no-cache openssl && openssl rand -base64 741 > /mongo-conf/mongodb-keyfile && chmod 600 /mongo-conf/mongodb-keyfile && chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-1:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    depends_on:
        - mongo-keys
    networks:
      replica-set:
  
  # Secondary 1
  mongo2:
    container_name: mongo2
    image: mongo:latest
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    depends_on:
        - mongo-keys
    networks:
      replica-set:
  
  # Secondary 2
  mongo3:
    container_name: mongo3
    image: mongo:latest
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-3:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet rs0'
    depends_on:
        - mongo-keys
    networks:
      replica-set:
  

